import { motionId } from './motion-id';

export { motionId } from './motion-id';

/** Doc page for a key — hash is always `#${motionId(keys)}`. */
const motionPages: Record<string, string> = {
  h: '/docs/motions/basic',
  l: '/docs/motions/basic',
  j: '/docs/motions/basic',
  k: '/docs/motions/basic',
  Space: '/docs/motions/basic',
  BS: '/docs/motions/basic',
  Backspace: '/docs/motions/basic',
  'Ctrl-h': '/docs/motions/basic',
  'Ctrl-p': '/docs/motions/basic',
  'Ctrl-j': '/docs/motions/basic',
  'Ctrl-n': '/docs/motions/basic',
  gj: '/docs/motions/basic',
  gk: '/docs/motions/basic',
  '-': '/docs/motions/basic',
  '+': '/docs/motions/basic',
  _: '/docs/motions/basic',
  Enter: '/docs/motions/basic',
  'Ctrl-m': '/docs/motions/basic',

  w: '/docs/motions/words',
  W: '/docs/motions/words',
  e: '/docs/motions/words',
  E: '/docs/motions/words',
  b: '/docs/motions/words',
  B: '/docs/motions/words',
  ge: '/docs/motions/words',
  gE: '/docs/motions/words',

  '0': '/docs/motions/lines',
  '^': '/docs/motions/lines',
  $: '/docs/motions/lines',
  g_: '/docs/motions/lines',
  '|': '/docs/motions/lines',
  g0: '/docs/motions/lines',
  'g^': '/docs/motions/lines',
  'g$': '/docs/motions/lines',
  gm: '/docs/motions/lines',
  gM: '/docs/motions/lines',
  gg: '/docs/motions/lines',
  G: '/docs/motions/lines',
  go: '/docs/motions/lines',
  'Ctrl-End': '/docs/motions/lines',
  'Ctrl-Home': '/docs/motions/lines',
  '{count}%': '/docs/motions/lines',

  '(': '/docs/motions/sentences',
  ')': '/docs/motions/sentences',
  '{': '/docs/motions/sentences',
  '}': '/docs/motions/sentences',
  '[[': '/docs/motions/sections',
  ']]': '/docs/motions/sections',
  '[]': '/docs/motions/sections',
  '][': '/docs/motions/sections',

  'f{char}': '/docs/motions/search',
  'F{char}': '/docs/motions/search',
  't{char}': '/docs/motions/search',
  'T{char}': '/docs/motions/search',
  ';': '/docs/motions/search',
  ',': '/docs/motions/search',
  '*': '/docs/motions/search',
  '#': '/docs/motions/search',
  'g*': '/docs/motions/search',
  'g#': '/docs/motions/search',
  n: '/docs/motions/search',
  N: '/docs/motions/search',
  gn: '/docs/motions/search',
  gN: '/docs/motions/search',
  gd: '/docs/motions/search',
  gD: '/docs/motions/search',
  '/': '/docs/motions/search',
  '?': '/docs/motions/search',
  '/pattern': '/docs/motions/search',
  '?pattern': '/docs/motions/search',
  '1gd': '/docs/motions/search',
  '1gD': '/docs/motions/search',

  iw: '/docs/motions/text-objects',
  aw: '/docs/motions/text-objects',
  iW: '/docs/motions/text-objects',
  aW: '/docs/motions/text-objects',
  ip: '/docs/motions/text-objects',
  ap: '/docs/motions/text-objects',
  is: '/docs/motions/text-objects',
  as: '/docs/motions/text-objects',
  it: '/docs/motions/text-objects',
  at: '/docs/motions/text-objects',
  'i(': '/docs/motions/text-objects',
  'i)': '/docs/motions/text-objects',
  ib: '/docs/motions/text-objects',
  ab: '/docs/motions/text-objects',
  "i\"": '/docs/motions/text-objects',
  "a\"": '/docs/motions/text-objects',
  "i'": '/docs/motions/text-objects',
  "a'": '/docs/motions/text-objects',
  'i`': '/docs/motions/text-objects',
  'a`': '/docs/motions/text-objects',
  'i[': '/docs/motions/text-objects',
  'a[': '/docs/motions/text-objects',
  'i]': '/docs/motions/text-objects',
  'a]': '/docs/motions/text-objects',
  'i{': '/docs/motions/text-objects',
  'a{': '/docs/motions/text-objects',
  'i}': '/docs/motions/text-objects',
  'a}': '/docs/motions/text-objects',
  'iB': '/docs/motions/text-objects',
  'aB': '/docs/motions/text-objects',
  'i<': '/docs/motions/text-objects',
  'a<': '/docs/motions/text-objects',
  'i>': '/docs/motions/text-objects',
  'a>': '/docs/motions/text-objects',
  'a(': '/docs/motions/text-objects',
  'a)': '/docs/motions/text-objects',

  '%': '/docs/motions/matching',
  '[(': '/docs/motions/matching',
  '[{': '/docs/motions/matching',
  '])': '/docs/motions/matching',
  ']}': '/docs/motions/matching',
  ']m': '/docs/motions/matching',
  ']M': '/docs/motions/matching',
  '[m': '/docs/motions/matching',
  '[M': '/docs/motions/matching',
  '[#': '/docs/motions/matching',
  ']#': '/docs/motions/matching',
  '[/': '/docs/motions/matching',
  ']/': '/docs/motions/matching',
  '[*': '/docs/motions/matching',
  ']*': '/docs/motions/matching',

  H: '/docs/motions/scrolling',
  M: '/docs/motions/scrolling',
  L: '/docs/motions/scrolling',
  'Ctrl-f': '/docs/motions/scrolling',
  'Ctrl-b': '/docs/motions/scrolling',
  'Ctrl-d': '/docs/motions/scrolling',
  'Ctrl-u': '/docs/motions/scrolling',
  zz: '/docs/motions/scrolling',
  zt: '/docs/motions/scrolling',
  zb: '/docs/motions/scrolling',
  'z.': '/docs/motions/scrolling',
  'z-': '/docs/motions/scrolling',
  zEnter: '/docs/motions/scrolling',

  '[z': '/docs/motions/folds',
  ']z': '/docs/motions/folds',
  zj: '/docs/motions/folds',
  zk: '/docs/motions/folds',

  "''": '/docs/motions/jumps',
  '``': '/docs/motions/jumps',
  'Ctrl-o': '/docs/motions/jumps',
  'Ctrl-i': '/docs/motions/jumps',
  'g;': '/docs/motions/jumps',
  'g,': '/docs/motions/jumps',

  d: '/docs/operators/delete',
  dd: '/docs/operators/delete',
  D: '/docs/operators/delete',
  x: '/docs/operators/delete',
  X: '/docs/operators/delete',
  c: '/docs/operators/change',
  'cc / S': '/docs/operators/change',
  cc: '/docs/operators/change',
  C: '/docs/operators/change',
  s: '/docs/operators/change',
  y: '/docs/operators/yank',
  'yy / Y': '/docs/operators/yank',
  yy: '/docs/operators/yank',
  Y: '/docs/operators/yank',
  p: '/docs/operators/yank',
  P: '/docs/operators/yank',
  v: '/docs/getting-started/modes',
  V: '/docs/getting-started/modes',
  'Ctrl-v': '/docs/getting-started/modes',
  i: '/docs/getting-started/modes',
  a: '/docs/getting-started/modes',
  I: '/docs/getting-started/modes',
  A: '/docs/getting-started/modes',
  o: '/docs/getting-started/modes',
  O: '/docs/getting-started/modes',
  S: '/docs/getting-started/modes',
  Esc: '/docs/getting-started/modes',

  '2dw': '/docs/getting-started/counts',
};

/** Alias key → canonical Motion `keys` value used for the hash. */
const aliasIds: Record<string, string> = {
  Backspace: 'BS',
  Enter: '+',
  'Ctrl-m': '+',
  'Ctrl-Home': 'gg',
  'Ctrl-p': 'k',
  'Ctrl-j': 'j',
  'Ctrl-n': 'j',
  '[*': '[/',
  ']*': ']/',
  cc: 'cc / S',
  yy: 'yy / Y',
  Y: 'yy / Y',
  Tab: 'Ctrl-i',
  '1gd': 'gd',
  '1gD': 'gD',
  '/pattern': '/',
  '?pattern': '?',
};

export function hrefForKeys(keys: string): string | undefined {
  const canonical = aliasIds[keys] ?? keys;
  const page = motionPages[keys] ?? motionPages[canonical];
  if (!page) return undefined;
  return `${page}#${motionId(canonical)}`;
}

/**
 * Split operator+motion combos like d$, dl, c$ into parts we can link separately.
 * Returns null when the key should be linked as a single unit.
 */
export function splitLinkedKeys(keys: string): string[] | null {
  if (hrefForKeys(keys)) return null;
  const m = /^(?<op>[dcy])(?<rest>.+)$/.exec(keys);
  if (!m?.groups) return null;
  const { op, rest } = m.groups;
  if (hrefForKeys(op) && hrefForKeys(rest)) return [op, rest];
  return null;
}
